### ISSUE TITLE
How to apply the package to multiple spatial transcriptomics datasets?

### ISSUE THREAD

**Issue by yunbokai** [lhc17/HoloNet#8]
Hi, Thanks for the great package. I wonder  know how to apply this package to multiple spatial transcriptomics datasets as Cellchat V2 did in https://htmlpreview.github.io/?https://github.com/jinworks/CellChat/blob/master/tutorial/CellChat_analysis_of_multiple_spatial_transcriptomics_datasets.html. Can you give me any advice?

**Comment by lhc17** [comment]
Thanks for your usage. I'm sorry that there is no method to analyze multiple spatial transcriptomics datasets comprehensively in this version of HoloNet. Maybe in the future, we will include this function.  You can firstly select representative slides for analysis. We look forward to your continued attention to our method.

**Comment by yunbokai** [comment]
Thanks!
